CREATE DATABASE delilah_resto;
USE delilah_resto;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	fullname VARCHAR(100) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	mobile VARCHAR(25) NOT NULL UNIQUE,
	address VARCHAR(50) NOT NULL,
	is_deleted TINYINT NOT NULL DEFAULT 0,
	is_admin TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY(id)
) AUTO_INCREMENT = 1000;

CREATE TABLE products(
	id INT NOT NULL AUTO_INCREMENT,
	description VARCHAR(50) NOT NULL,
	picture VARCHAR(255) NOT NULL,
	price DECIMAL(6,2) NOT NULL,
	is_deleted TINYINT NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
) AUTO_INCREMENT = 100;

CREATE TABLE payment(
	id INT NOT NULL AUTO_INCREMENT,
	method VARCHAR(25) NOT NULL,
	PRIMARY KEY(id)
) AUTO_INCREMENT = 10;

CREATE TABLE status(
	id INT NOT NULL AUTO_INCREMENT,
	status VARCHAR(25) NOT NULL,
	PRIMARY KEY(id)
) AUTO_INCREMENT = 50;

CREATE TABLE orders(
	id INT NOT NULL AUTO_INCREMENT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	is_deleted TINYINT NOT NULL DEFAULT 0,
	payment_id INT NOT NULL,
	status_id INT NOT NULL,
	user_id INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(payment_id) REFERENCES payment(id),
	FOREIGN KEY(status_id) REFERENCES status(id)
) AUTO_INCREMENT = 10000;

CREATE TABLE order_details(
	id INT NOT NULL AUTO_INCREMENT,
	order_id INT NOT NULL,
	product_id INT NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(order_id) REFERENCES orders(id),
	FOREIGN KEY(product_id) REFERENCES products(id)
) AUTO_INCREMENT = 50000;