CREATE DATABASE delilah_resto;
USE delilah_resto;

CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT = 1000,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	fullname VARCHAR(100) NOT NULL,
	email VARCHAR(50) NOT NULL,
	phone VARCHAR(25) NOT NULL,
	address VARCHAR(50) NOT NULL,
	is_deleted TINYINT(1) NOT NULL DEFAULT 0,
	is_admin TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id)
);

CREATE TABLE products(
	id INT NOT NULL AUTO_INCREMENT = 100,
  description VARCHAR(50) NOT NULL,
  picture VARCHAR(255) NOT NULL,
  price DECIMAL(6,2) NOT NULL,
	is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id),
);

CREATE TABLE orders(
	id INT NOT NULL AUTO_INCREMENT = 10000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(255) NOT NULL,
  payment VARCHAR(100) NOT NULL,
	status VARCHAR(25) NOT NULL,
	is_deleted TINYINT(1) NOT NULL DEFAULT 0,
	user_id INT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);